Solved typo in Creating Steps page causing 404
trywilco/wilco-docs pull request #25
Opened 2022-12-08 16:20 UTC by hussainshaikh12

**Describe the bug**
triggers-and-payload page causing 404 on the Creating Steps page

**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://dev.trywilco.com/docs/building-your-quest/creating-steps.html
2. Click Triggers and Payload link
3. It causes a 404 because a simple typo in the link
triggers-and-payload.html should be ---> triggers-and-**payloads**.html

2022-12-09 03:30 UTC, hussainshaikh12 commented
@AssafKr @darmalovan can you please review my pr

2022-12-09 17:59 UTC, shem8 requested changes
Thank you for contributing!
But you changed the url (and thus, break the link), I guess you wanted to change to text

2022-12-10 12:10 UTC, hussainshaikh12 commented
> 

Sorry I didn't  get what I was supposed to do. The live site is still causing a 404 because of the incorrect link. I just changed the broken link to the correct url.  🤔

2022-12-11 09:35 UTC, shem8 approved these changes
Oh, nice!

2022-12-11 12:22 UTC, peri-wilco commented
Thanks a lot for bringing this up! I've opened #29 to address this using `{% link %}` to prevent broken links in the future. Closing this one.

2022-12-11 12:22 UTC, closed without merging